spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa :
    database-platform : org.springframework.orm.jpa.vendor.Database.MYSQL
    generate-ddl : true
    show-sql : true
    hibernate :
      ddl-auto : update
    properties :
      hibernate :
        globally_quoted_identifiers : true
        dialect : org.hibernate.dialect.MySQLDialect
        format_sql : true
